bitsofgood/pencils-for-success

- package-lock.json
- package.json
- src/pages/_app.tsx
Adds chakra-ui, the component library of choice, to the project. Adds the `ChakraProvider` to the root app component of NextJS
> chore(deps): install chakra-ui and add ChakraProvider

- prisma/schema.prisma
Updated schema for User, Admin, Chapter, and Recipient.
- Closes #8 
- Closes #9 
Tested that the schema is valid. Ensured that all the users have a relation
> Add prisma schema for initial types

- .github/workflows/ci.yml
Description of proposed changes
- Closes #1
- Open landing page
- Saw that logo displayed Pencils for Success logo properly
> fix(ci): add missing pre-req steps to sync-db job

- prisma/schema.prisma
Description of proposed changes
- Closes #1
- Open landing page
- Saw that logo displayed Pencils for Success logo properly
> refactor(schema): rename admin/chapter/recipient user models

- prisma/schema.prisma
Added the recipient and chapter models in schema.
- Closes #18 
- Tested adding new data points
> Ethan ayush/18/chapter rec models

- .github/workflows/ci.yml
We care more about correctness of the database schema rather than
mock data so the --accept-data-loss option is used here.
Description of proposed changes
- Closes #1
- Open landing page
- Saw that logo displayed Pencils for Success logo properly
> fix(ci): add accept data loss option to prisma db push

- .github/workflows/ci.yml
Description of proposed changes
- Closes #1
- Open landing page
- Saw that logo displayed Pencils for Success logo properly
> feat(ci): add seed script to dev deploy CI

- package-lock.json
- package.json
- src/pages/api/admin/login.ts
- src/utils/session.ts
Added the needed login endpoint that checks accepts a username and password and checks the password against hashed passwords in the DB. Returns session info if valid, if not 405 error.
- Closes #12 
- Tested if the user existed in the database but passwords didn't match
- Tested if the user existed in the database but passwords matched
- Tested if the user wasn't in the database.
> Ethan ayush/12/login endpoint

- src/pages/api/recipients/index.ts
- src/utils/prisma-validation.ts
Add new endpoint to add a new recipient for a chapter
- Closes #65 
- Login as chapter user
- Tested new recipient creation endpoint
> Add new recipient

- src/pages/api/recipients/[recId]/supply-requests.ts
- src/utils/api-types.ts
- src/utils/prisma-validation.ts
Addeds a post request to create supplyRequests
- Closes #76 
- Login as authenticated user versus not and see if post request is allowed
- Test with missing parameters
- Test with and without an item array
> Ethan ayush/76/create supply requests

- prisma/schema.prisma
- src/pages/api/recipients/[recId].ts
Endpoint for deleting recipients
- Closes #97 
- Access the endpoint not logged in or not as an Authorized User
- Try to delete Recipient that doesn't exist
- Try to delete a Recipient that's valid
> feat(backend): del-recipient-endpoint

- package-lock.json
- package.json
- src/components/RecipientCard.tsx
- src/components/RecipientDetails.tsx
- src/components/recipient-modals/NewRecipientModal.tsx
- src/pages/api/chapters/[chapterId]/recipients.ts
- src/pages/api/recipients/index.ts
- src/pages/chapter/index.tsx
- src/providers/RecipientsProvider.tsx
Add a new sidebar to display recipients. On clicking a recipient, the details for the selected recipient will be shown. Note #67 will be added to the current placeholder.
- Closes #98
- Login as a chapter user.
- Visit `/chapter` endpoint. It should display the list of recipients.
- Click on a recipient. It should expand the card and show supply requests for it.
- On clicking the menu for a recipient, it should show the option to edit or delete the recipient (implementation in a different PR).
> #98 Update Chapter Dashboard

- src/pages/api/recipients/[recId].ts
Added a new endpoint `GET /api/recipients/:id` that will fetch data for the recipient based on the provided id. The only authorized users of this endpoint are:
- Chapter user that owns this recipient
- The recipient user that is currently logged in and is associated with the given id.
- Closes #92
**Unauthenticated User**
- Logout and ensure no cookies are saved.
- Make API request to `GET /api/recipients/2`. It should return a 401 unauthorized error.
**Authorized Chapter User**
- Login as a chapter user for Georgia.
- Make API request to `GET /api/recipients/2`. It should return details about the recipient.
**Unauthorized Chapter User**
- Login as a chapter user for a different chapter.
- Make API request to `GET /api/recipients/2`. It should return a 401 …
> Add get endpoint for fetching recipients

- package-lock.json
- package.json
- prisma/schema.prisma
- prisma/seed.ts
- src/components/SupplyRequestList.tsx
- src/pages/_app.tsx
- src/pages/api/recipients/[recId]/supply-requests.ts
- src/pages/recipient/index.tsx
- src/pages/recipient/login.tsx
- src/types/react-table.d.ts
- src/utils/api-types.ts
- src/utils/api.ts
- src/utils/middlewares/auth.ts
- src/utils/prisma-validation.ts
Contains all changes from #114. Made a separate PR due to merge conflict issues with that branch
- Closes #67 
-
> Supply Request List

- src/pages/admin/index.tsx
- src/pages/api/admin/login.ts
- src/pages/api/chapters/[chapterId].ts
- src/pages/api/chapters/[chapterId]/recipients.ts
- src/pages/api/chapters/index.ts
- src/pages/api/chapters/login.ts
- src/pages/api/chapters/users/[userId].ts
- src/pages/api/items/index.tsx
- src/pages/api/recipients/[recId].ts
- src/pages/api/recipients/[recId]/supply-requests.ts
- src/pages/api/recipients/index.ts
- src/pages/api/recipients/login.ts
- src/pages/chapter/index.tsx
- src/pages/recipient/index.tsx
- src/prisma-client.ts
- src/utils/middlewares/auth.ts
Prisma clients will be instantiated via the `src/prisma-client.ts` module. This increases the likelihood of client re-use.
Addresses #122
> Minimize prisma client instances

- src/pages/api/admin.ts
Endpoint to edit admin info
- Closes #134 
- Tested updating without being authenticated
- Tried entering password and username that were not valid
- Tried entering username that already existed in the db
> feat(backend): update-admin

- src/pages/api/recipients/[recId]/supply-requests/[supplyRequestId].ts
- src/utils/prisma-validation.ts
Added a new endpoint to be able to edit supply requests
- Closes #75 
Checked that the endpoint worked as an authenticated user.
> feat(backend): add edit supply request endpoint

- src/pages/api/recipients/[recId].ts
Added endpoint to edit recipient info
- Closes #95 
- Logged in as user an ensured you can edit recipient fino
> feat(backend): edit recipeint info

- src/pages/api/admin/index.ts
Added endpoint to retrieve admin info
- Closes #133 
- Tested getting the admin username
> Add endpoint to retrieve admin info

- src/components/RecipientCard.tsx
- src/components/recipient-modals/DeleteRecipientModal.tsx
- src/components/recipient-modals/RecipientModalController.tsx
- src/pages/api/recipients/[recId].ts
- src/pages/chapter/index.tsx
- src/providers/RecipientModalProvider.tsx
- src/providers/RecipientsProvider.tsx
Allow chapter users to delete recipients after confirmation prompt.
List of related issues/PRs and the type of association.
- Closes #131 
- Login as authenticated chapter user
- Create new test recipient
- Delete new test recipient
> Varsh emily/131/delete recipient prompt

- src/components/navbars/DonorNavbar.tsx
- src/components/navbars/DonorNavbarDropDown.tsx
- src/pages/index.tsx
- src/providers/DonorProvider.tsx
Added a dropdown on the main page of the website that allows you to select a chapter
- Closes #150 
- Run the website
- Select a chapter in the dropdown
- To see if the current chapter id is saved, you can import activeChapterId from DonorContext (in DonorProvider) and print out that value in the "handleSelect" method.
> Varsh emily/150/chapter dropdown

- src/pages/api/chapters/[chapterId]/recipients.ts
Needed for the donor dashboard #159
> Make recipients visible to all in chapter recipients endpoint

- src/components/TopSupplyRequests.tsx
- src/pages/api/chapters/[chapterId]/supply-requests/top.tsx
Fixed updating the top supply request. Now, it just returns an array of strings
- Closes #160 
Tested that the new endpoint is working as expected
> fix: update top supply requests

- src/components/Login.tsx
- src/components/RecipientCard.tsx
- src/components/RecipientDetails.tsx
- src/components/RecipientSidePanel.tsx
- src/components/SupplyRequestList.tsx
- src/components/TopSupplyRequests.tsx
- src/components/credential-modals/EditCredentialsAdminForm.tsx
- src/components/credential-modals/EditCredentialsChapterForm.tsx
- src/components/credential-modals/EditCredentialsModal.tsx
- src/components/credential-modals/ViewCredentialsModal.tsx
- src/pages/admin/index.tsx
- src/pages/api/chapters/[chapterId]/index.ts
- src/pages/chapter/index.tsx
- src/pages/recipient/index.tsx
- src/providers/CredentialsModalProvider.tsx
- Added styled login screen
- Added chapter info modal and edit functionality
- Fixed white space issue
- Fixed recipient side panel styling issues
- Altered supply list style slightly to enhance usability
- Closes #179 
- Closes #176 
- Click around the app
> feat(ui): login screen, fix bug issues, added chapter info modal

- src/components/RecipientSidePanel.tsx
- src/components/recipient-modals/EditRecipientModal.tsx
- src/pages/chapter/index.tsx
- src/pages/recipient/index.tsx
For recipient page, add new edit modal when edit info button is clicked on the left side.
- Closes #180 
- Logged in to recipient
- Tested that opening and saving the modal worked
> Add new edit modal for recipient
